[node]
eth_chain_id = 560048
ethereum_rpc = "https://rpc.ankr.com/eth_hoodi/6852445d1ba0cde4f6506223f888d4a756889df7254b65674820c4324ab7eeba"
drosera_rpc = "https://relay.hoodi.drosera.io"
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.DustAttackTrap]
path = "out/DustAttackTrap.sol/DustAttackTrap.json"
response_contract = "0x4C832Bb03356aAA2eDB6eC50Fe62F3Fc2d74E48c"
response_function = "respondToDustAttack(bytes)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 10
block_sample_size = 10
start_block = "latest"
trap_address = "0x203a658Dda3a4cf44C12c18bCfde0F7F15693F32"
private_trap = true
whitelist = ["0x040221e51b6232Ad8C9d553B806E0C7A00D1ae4C"]
address = "0xCd4d2Be4364E080c9B838fA576B98dC2ee716199"
